### ISSUE TITLE
sayHello n times

### ISSUE THREAD

**Issue by MadhuBeesetty** [garageScript/algorithm#3]
Input: a number

Input: 3
Output: Hello Hello Hello

**Comment by songz** [comment]
input: 3

console.log('Hello');
console.log('Hello');
console.log('Hello');

**Comment by saumya665** [comment]
use console.log no need to return

**Comment by songz** [comment]
NO TEST NEEDED HERE!

**Comment by songz** [comment]
this is very similar to #4 so we are deleting this problem!
